name: Automatic testing for the Caching Client

on:
  push:
    branches: [ master ]
    paths: [ 'cachingClient/**' ]
  pull_request:
    paths:
    paths: [ 'cachingClient/**' ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd cachingClient/
      - run: npm ci 
      - run: npm test